language: python
python:
  - "3.6"
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest

before_script: sh -e /etc/init.d/xvfb start

install:
  - pip install mypy
  - pip install selenium
  - pip install thor
  - pip install markdown


script: "make -e"
