language: python
python:
  - "3.6"
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - pip install mypy
  - pip install selenium
  - pip install thor
  - pip install markdown


script: "make -e"
